# Generated by Django 3.1.3 on 2020-11-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('dependants', models.IntegerField()),
                ('applicantincome', models.IntegerField()),
                ('coapplicantincome', models.IntegerField()),
                ('loanamt', models.IntegerField()),
                ('loantern', models.IntegerField()),
                ('credithistory', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=15)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('graduatededucation', models.CharField(choices=[('Graduated', 'Graduated'), ('Not_Graduated', 'Not_Graduated')], max_length=15)),
                ('selfemployed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('area', models.CharField(choices=[('Rural', 'Rural'), ('SemiUrban', 'SemiUrban'), ('Urban', 'Urban')], max_length=15)),
            ],
        ),
    ]
